fastp:
  t: 2
  m: 1
kraken2:
  t: 2
  m: 81
checkm:
  t: 2
  m: 1
megahit:
  t: 2
  m: 2
metaphlan4:
  t: 2
  m: 31
align:
  t: 2
  m: 2
binning:
  t: 2
  m: 2
gtdbtk:
  t: 2
  m: 81
drep:
  t: 2
  m: 4

diversity: Normal
novelty: Low
resources: Shortage
location: test
adapter1: AGCT
adapter2: AGCT
checkm_db: .
mp_db: .
kraken2_db: .
target: all
metadata: metadata.tsvdiversity: Normal
novelty: Low
resources: Shortage
location: test
adapter1: AGCT
adapter2: AGCT
checkm_db: .
mp_db: .
kraken2_db: .
target: all
metadata: metadata.tsvdiversity: Normal
novelty: Low
resources: Shortage
location: test
adapter1: AGCT
adapter2: AGCT
checkm_db: .
mp_db: .
kraken2_db: .
target: all
metadata: metadata.tsv